import type { Category } from "@/content/types";

export const categories: Category[] = [
  {
    slug: "coffee-basics",
    name: "커피 기초",
    description: "커피의 구조와 한 잔이 만들어지는 전체 흐름",
    icon: "seed",
    accent: "olive",
  },
  {
    slug: "origin-and-green",
    name: "산지와 생두",
    description: "품종, 재배 환경, 가공과 생두 품질",
    icon: "mountain",
    accent: "sage",
  },
  {
    slug: "roasting",
    name: "로스팅",
    description: "열 전달부터 프로파일 설계와 품질 관리",
    icon: "flame",
    accent: "copper",
  },
  {
    slug: "brewing",
    name: "추출",
    description: "물, 분쇄도, 비율로 맛을 설계하는 방법",
    icon: "drop",
    accent: "blue",
  },
  {
    slug: "sensory",
    name: "센서리",
    description: "커핑, 향미 언어와 관능평가의 원리",
    icon: "nose",
    accent: "berry",
  },
  {
    slug: "cafe-and-gear",
    name: "카페와 장비",
    description: "에스프레소 머신, 그라인더와 바 운영",
    icon: "cup",
    accent: "sand",
  },
  {
    slug: "coffee-science",
    name: "커피 과학",
    description: "화학, 물리와 미생물학으로 읽는 향미의 원인",
    icon: "drop",
    accent: "blue",
  },
  {
    slug: "history-and-culture",
    name: "커피 역사와 문화",
    description: "커피의 이동, 커피하우스와 지역별 음용 문화",
    icon: "mountain",
    accent: "copper",
  },
  {
    slug: "sustainability-and-trade",
    name: "지속가능성과 거래",
    description: "기후, 농가 생계, 가격과 책임 있는 공급망",
    icon: "seed",
    accent: "sage",
  },
  {
    slug: "cafe-operations",
    name: "카페 운영과 품질",
    description: "워크플로, 위생, 원가와 일관된 품질 관리",
    icon: "cup",
    accent: "sand",
  },
  {
    slug: "drinks-and-recipes",
    name: "음료와 레시피",
    description: "세계의 커피 음료, 우유와 재료의 설계 원리",
    icon: "cup",
    accent: "berry",
  },
  {
    slug: "coffee-and-health",
    name: "커피와 건강",
    description: "카페인, 수면과 섭취 정보를 근거 중심으로 읽기",
    icon: "nose",
    accent: "olive",
  },
];
