import type { Accent } from "@/content/types";

// 커피 지식 퀴즈. 각 문항은 위키 문서에서 근거를 확인할 수 있어야 하며
// (source = slug), 해설은 정답 이유와 흔한 오해를 함께 짚습니다.
// 문체·근거 기준은 docs/EDITORIAL.md를 따릅니다.
export type QuizQuestion = {
  id: string;
  level: "입문" | "중급" | "전문";
  category: string;
  accent: Accent;
  question: string;
  choices: string[];
  answer: number; // index into choices
  explanation: string;
  source: string; // article slug
  sourceLabel: string;
};

export const quiz: QuizQuestion[] = [
  {
    id: "q-tds-yield",
    level: "입문",
    category: "추출",
    accent: "blue",
    question: "농도(TDS)와 추출 수율의 관계로 옳은 것은?",
    choices: [
      "둘은 같은 값을 다르게 부르는 이름이다",
      "농도는 잔의 진하기, 수율은 원두에서 빠져나온 성분의 비율이다",
      "수율이 높으면 항상 농도도 높다",
      "농도가 높으면 항상 과다 추출이다",
    ],
    answer: 1,
    explanation:
      "농도는 음료에 녹아 있는 고형분의 비율이고, 수율은 투입한 원두 중 얼마가 음료로 이동했는지를 나타냅니다. 물을 적게 쓰면 수율이 낮아도 진할 수 있어 두 값을 함께 봐야 합니다.",
    source: "extraction-basics",
    sourceLabel: "추출의 기본",
  },
  {
    id: "q-acidity",
    level: "입문",
    category: "센서리",
    accent: "berry",
    question: "커피 평가에서 '산미(acidity)'는 보통 어떤 의미로 쓰입니까?",
    choices: [
      "불쾌하게 시큼한 맛",
      "밝고 생동감을 주는 긍정적인 신맛의 인상",
      "pH가 낮다는 화학적 사실만을 가리킨다",
      "로스팅이 덜 되었다는 신호",
    ],
    answer: 1,
    explanation:
      "산미는 평가 용어로, 과일의 즙 같은 밝은 인상을 가리킵니다. 날카롭고 불쾌한 신맛(sourness)과는 구분해서 씁니다.",
    source: "sensory-attributes",
    sourceLabel: "커피 평가의 언어",
  },
  {
    id: "q-body",
    level: "입문",
    category: "센서리",
    accent: "berry",
    question: "'바디'가 가리키는 것은?",
    choices: [
      "커피의 카페인 함량",
      "입안에서 느끼는 무게감과 질감",
      "향의 강도",
      "로스팅 정도",
    ],
    answer: 1,
    explanation:
      "바디는 맛이 아니라 촉감입니다. 오일과 미분이 많이 통과하는 추출 방식에서 무거워지는 경향이 있습니다.",
    source: "sensory-attributes",
    sourceLabel: "커피 평가의 언어",
  },
  {
    id: "q-cupping-ratio",
    level: "중급",
    category: "센서리",
    accent: "berry",
    question: "널리 통용되어 온 SCA 커핑의 기준 비율에 가장 가까운 것은?",
    choices: [
      "물 150ml당 커피 약 8.25g",
      "물 150ml당 커피 약 20g",
      "물 100ml당 커피 약 15g",
      "정해진 비율이 없다",
    ],
    answer: 0,
    explanation:
      "약 1:18.2에 해당하는 비율로, 용기 용량에 비례해 조정합니다. 다만 세부 수치는 해당 시점의 SCA 공식 문서를 확인해야 합니다.",
    source: "sca-cupping-protocol",
    sourceLabel: "SCA 커핑 프로토콜",
  },
  {
    id: "q-cva",
    level: "중급",
    category: "센서리",
    accent: "berry",
    question: "CVA(Coffee Value Assessment)의 가장 큰 변화는?",
    choices: [
      "점수를 200점 만점으로 바꿨다",
      "기술적(무엇이 느껴지는가) 평가와 선호(얼마나 좋은가) 평가를 분리했다",
      "커핑을 없애고 기계 분석으로 대체했다",
      "산미 항목을 삭제했다",
    ],
    answer: 1,
    explanation:
      "두 질문은 평가자와 목적이 다르기 때문에 분리하는 것이 핵심입니다. 점수 산식도 전통 폼과 달라 두 체계의 점수는 직접 비교할 수 없습니다.",
    source: "sca-cupping-protocol",
    sourceLabel: "SCA 커핑 프로토콜",
  },
  {
    id: "q-triangle",
    level: "전문",
    category: "센서리",
    accent: "berry",
    question: "삼각 테스트(트라이앵귤레이션)에서 아무렇게나 골라도 맞을 확률은?",
    choices: ["1/2", "1/3", "1/6", "0에 가깝다"],
    answer: 1,
    explanation:
      "세 잔 중 하나를 고르므로 우연 확률은 1/3입니다. 그래서 한두 번의 성공은 증거가 되지 못하고, 반복 시행에서 기준표(ISO 4120 등)의 임계값을 넘는지로 판단합니다.",
    source: "sensory-data-analysis",
    sourceLabel: "관능 데이터",
  },
  {
    id: "q-calibration",
    level: "전문",
    category: "센서리",
    accent: "berry",
    question: "Q 그레이더 자격이 주기적 재교정을 요구하는 이유로 가장 적절한 것은?",
    choices: [
      "자격증 발급 수수료를 받기 위해",
      "감각과 채점 습관이 시간이 지나며 표류하기 때문",
      "커피 품종이 매년 바뀌기 때문",
      "장비 사양이 매년 바뀌기 때문",
    ],
    answer: 1,
    explanation:
      "자격의 핵심은 뛰어난 미각이 아니라 교정된 미각입니다. 기준에 다시 맞추는 절차가 평가의 신뢰를 지탱합니다.",
    source: "q-grader-certification",
    sourceLabel: "Q 그레이더",
  },
  {
    id: "q-flavor-wheel",
    level: "입문",
    category: "센서리",
    accent: "berry",
    question: "향미 휠을 사용하는 올바른 방향은?",
    choices: [
      "바깥쪽 구체 표현부터 골라 안쪽으로 좁힌다",
      "안쪽 큰 범주에서 시작해 확신이 생기는 만큼 바깥쪽으로 간다",
      "휠에 적힌 향미가 모두 느껴져야 한다",
      "점수를 매기는 도구로 쓴다",
    ],
    answer: 1,
    explanation:
      "휠은 정답지가 아니라 어휘 지도입니다. 애매하면 안쪽 범주에서 멈추는 것이 과장된 표현보다 낫습니다.",
    source: "coffee-flavor-wheel",
    sourceLabel: "커피 향미 휠",
  },
  {
    id: "q-dtr",
    level: "전문",
    category: "로스팅",
    accent: "copper",
    question: "DTR(발달 시간 비율)에 대한 설명으로 옳은 것은?",
    choices: [
      "값이 높을수록 항상 품질이 좋다",
      "전체 로스팅 시간 중 1차 크랙 이후가 차지하는 비율이며 스타일에 따른 참고 지표다",
      "생두의 수분 함량을 뜻한다",
      "에스프레소 추출 시간의 비율이다",
    ],
    answer: 1,
    explanation:
      "필터 로스팅에서 15~25% 부근을 참고하는 경우가 흔하지만 품질 보증은 아닙니다. 배출 색도·감량률과 함께 묶어 봐야 합니다.",
    source: "roast-profile-design",
    sourceLabel: "로스트 프로파일 설계",
  },
  {
    id: "q-first-crack",
    level: "입문",
    category: "로스팅",
    accent: "copper",
    question: "로스팅에서 '1차 크랙'은 무엇입니까?",
    choices: [
      "생두에 금이 가는 결점",
      "내부 압력으로 원두가 팽창·파열하며 나는 소리",
      "로스터 기계의 경고음",
      "포장 시 발생하는 가스 배출",
    ],
    answer: 1,
    explanation:
      "발현(발달) 단계의 시작을 알리는 신호로 널리 쓰입니다. 온도계 값보다 기계 간 비교가 쉬운 편입니다.",
    source: "roasting-basics",
    sourceLabel: "로스팅 입문",
  },
  {
    id: "q-processing",
    level: "중급",
    category: "산지와 생두",
    accent: "sage",
    question: "워시드 가공의 특징으로 가장 적절한 것은?",
    choices: [
      "체리를 통째로 건조한다",
      "과육을 제거한 뒤 발효·세척을 거쳐 건조한다",
      "점액질을 전부 남긴 채 건조한다",
      "생두를 물에 삶는다",
    ],
    answer: 1,
    explanation:
      "내추럴은 체리째 건조, 허니는 점액질을 일부 남겨 건조합니다. 가공 방식은 향미 경향에 큰 영향을 줍니다.",
    source: "coffee-processing",
    sourceLabel: "가공 방식",
  },
  {
    id: "q-storage",
    level: "입문",
    category: "커피 기초",
    accent: "olive",
    question: "원두 보관에서 가장 큰 향미 손실이 일어나는 시점은?",
    choices: [
      "포장을 개봉하는 순간",
      "분쇄한 직후",
      "물을 붓는 순간",
      "냉장고에 넣는 순간",
    ],
    answer: 1,
    explanation:
      "표면적이 급격히 늘어나 향 성분이 빠르게 날아갑니다. 가능하면 마시기 직전에 갈아 신선도를 지키세요.",
    source: "coffee-storage",
    sourceLabel: "원두 보관",
  },
  {
    id: "q-immersion",
    level: "입문",
    category: "추출",
    accent: "blue",
    question: "다음 중 침지(immersion) 방식의 추출은?",
    choices: ["푸어오버(핸드드립)", "프렌치 프레스", "에스프레소", "배치 브루어"],
    answer: 1,
    explanation:
      "침지는 커피와 물을 함께 담가 두는 방식으로, 시간과 비율이 추출을 좌우합니다. 푸어오버·배치 브루어는 투과, 에스프레소는 가압 방식입니다.",
    source: "brew-methods",
    sourceLabel: "추출법 총람",
  },
  {
    id: "q-bloom",
    level: "입문",
    category: "추출",
    accent: "blue",
    question: "푸어오버에서 뜸(블룸)을 들이는 주된 이유는?",
    choices: [
      "커피를 미리 데우기 위해",
      "갇힌 가스를 내보내 이후 추출을 고르게 하기 위해",
      "향을 날려 보내기 위해",
      "필터 냄새를 제거하기 위해",
    ],
    answer: 1,
    explanation:
      "신선한 원두일수록 이산화탄소가 많아, 소량의 물로 30~45초 가스를 빼 주면 물길이 고르게 형성됩니다.",
    source: "home-brew-recipes",
    sourceLabel: "기본 레시피 모음",
  },
  {
    id: "q-moka",
    level: "중급",
    category: "추출",
    accent: "blue",
    question: "모카포트에 대한 설명으로 가장 정확한 것은?",
    choices: [
      "9기압으로 추출하는 가정용 에스프레소 머신이다",
      "증기압(대체로 1~2기압 수준)으로 물을 밀어 올리는 저압 가압 방식이다",
      "침지식 추출 도구다",
      "압력이 전혀 관여하지 않는다",
    ],
    answer: 1,
    explanation:
      "진하고 묵직한 커피가 나오지만, 압력·온도 특성이 에스프레소(약 9기압)와 달라 같은 음료로 보기는 어렵습니다.",
    source: "brew-methods",
    sourceLabel: "추출법 총람",
  },
  {
    id: "q-dualboiler",
    level: "중급",
    category: "카페와 장비",
    accent: "sand",
    question: "듀얼 보일러 에스프레소 머신의 핵심 장점은?",
    choices: [
      "예열이 필요 없다",
      "추출수와 스팀의 온도를 독립적으로 제어하며 동시 작업이 가능하다",
      "전기가 필요 없다",
      "그라인더가 내장되어 있다",
    ],
    answer: 1,
    explanation:
      "추출용과 스팀용 보일러가 분리되어 있어 서로 다른 요구 온도를 각각 안정적으로 유지할 수 있습니다.",
    source: "espresso-machines-grinders",
    sourceLabel: "머신과 그라인더",
  },
  {
    id: "q-e61",
    level: "전문",
    category: "카페와 장비",
    accent: "sand",
    question: "준상업 머신에서 흔히 보는 'E61 그룹헤드'의 유래는?",
    choices: [
      "61번째 시제품이라는 뜻",
      "1961년 파에마(Faema)가 상용화한 머신에서 유래",
      "그룹헤드의 지름(61mm)",
      "추출 온도 61℃를 뜻함",
    ],
    answer: 1,
    explanation:
      "파에마 E61은 전동 펌프 가압을 상용화했고, 그 그룹헤드 설계는 이후 준상업·가정용 머신의 표준처럼 이어졌습니다.",
    source: "espresso-machines-grinders",
    sourceLabel: "머신과 그라인더",
  },
  {
    id: "q-gear-priority",
    level: "입문",
    category: "카페와 장비",
    accent: "sand",
    question: "홈카페 장비 투자에서 흔히 가장 먼저 권장되는 것은?",
    choices: ["고급 드리퍼", "좋은 그라인더", "은도금 스푼", "대용량 서버"],
    answer: 1,
    explanation:
      "분쇄 균일성이 맛에 미치는 영향이 가장 크기 때문입니다. 그다음이 저울, 케틀 순으로 흔히 권장됩니다.",
    source: "brewing-gear-guide",
    sourceLabel: "추출 도구 가이드",
  },
  {
    id: "q-coldbrew-time",
    level: "입문",
    category: "추출",
    accent: "blue",
    question: "콜드브루(냉장 기준)의 일반적인 우림 시간 참고 범위는?",
    choices: ["30분~1시간", "3~4시간", "12~18시간", "3일 이상"],
    answer: 2,
    explanation:
      "낮은 온도에서는 성분이 천천히 녹아 나와 긴 접촉 시간으로 보완합니다. 실온이라면 8~12시간이 흔한 참고 범위입니다.",
    source: "cold-brew",
    sourceLabel: "콜드브루",
  },
  {
    id: "q-milk-temp",
    level: "중급",
    category: "카페와 장비",
    accent: "sand",
    question: "우유 스티밍에서 흔히 목표로 삼는 온도대는?",
    choices: ["약 40~45℃", "약 55~65℃", "약 75~85℃", "끓기 직전(95℃ 이상)"],
    answer: 1,
    explanation:
      "단맛과 질감이 잘 살아나는 범위로 자주 언급됩니다. 70℃를 넘기면 비린 맛과 거친 거품이 생기기 쉽습니다.",
    source: "milk-steaming",
    sourceLabel: "우유 스티밍",
  },
  {
    id: "q-seed-anatomy",
    level: "입문",
    category: "커피 기초",
    accent: "olive",
    question: "우리가 보통 '커피콩'이라고 부르는 것은 식물학적으로 무엇입니까?",
    choices: ["열매의 씨앗", "나무의 뿌리", "말린 꽃봉오리", "열매의 껍질만"],
    answer: 0,
    explanation:
      "커피 체리 안에는 보통 두 개의 씨앗이 마주 보고 자랍니다. 가공은 과육과 점액질, 파치먼트 등을 제거해 이 씨앗을 안정적으로 건조하는 과정입니다.",
    source: "coffee-cherry-to-bean",
    sourceLabel: "체리에서 생두까지",
  },
  {
    id: "q-cupping-purpose",
    level: "입문",
    category: "센서리",
    accent: "berry",
    question: "커핑에서 동일한 분쇄·비율·시간을 사용하는 주된 이유는?",
    choices: ["가장 맛있는 레시피를 찾기 위해", "시료 외의 변수를 줄여 비교하기 위해", "카페인을 제거하기 위해", "로스팅을 더 진행하기 위해"],
    answer: 1,
    explanation:
      "커핑은 판매용 레시피를 찾는 절차가 아니라 시료를 공통 조건에서 비교하는 평가 방법입니다.",
    source: "cupping-basics",
    sourceLabel: "커핑 입문",
  },
  {
    id: "q-green-structure",
    level: "중급",
    category: "커피 기초",
    accent: "olive",
    question: "생두의 세포벽과 저장 물질이 추출에 영향을 주는 까닭은?",
    choices: ["모든 성분이 같은 속도로 녹기 때문에", "로스팅과 분쇄 뒤에도 물질 이동 경로와 전구체가 되기 때문에", "카페인을 완전히 막기 때문에", "색만 결정하기 때문에"],
    answer: 1,
    explanation:
      "세포 구조와 전구체는 로스팅 반응, 기공과 취성, 분쇄 입자 안의 물질 이동에 연결됩니다.",
    source: "bean-structure-compounds",
    sourceLabel: "생두의 구조와 성분",
  },
  {
    id: "q-water-alkalinity",
    level: "중급",
    category: "추출",
    accent: "blue",
    question: "커피 물에서 알칼리도가 지나치게 높을 때 나타나기 쉬운 변화는?",
    choices: ["산미가 완충되어 둔하게 느껴진다", "카페인이 모두 사라진다", "물의 온도가 자동으로 낮아진다", "분쇄 입자가 커진다"],
    answer: 0,
    explanation:
      "알칼리도는 산을 중화하는 능력입니다. 지나치면 커피의 산미가 둔해질 수 있지만, 적정 수준은 장비와 맛의 균형에 필요합니다.",
    source: "water-for-coffee",
    sourceLabel: "커피를 위한 물",
  },
  {
    id: "q-grind-distribution",
    level: "중급",
    category: "카페와 장비",
    accent: "sand",
    question: "그라인더를 평균 입도 하나로만 비교하기 어려운 이유는?",
    choices: ["입자는 모두 완전히 같은 크기이기 때문에", "미분과 큰 입자를 포함한 분포가 흐름과 추출을 함께 바꾸기 때문에", "분쇄는 향미와 무관하기 때문에", "버는 원두에 닿지 않기 때문에"],
    answer: 1,
    explanation:
      "같은 평균값도 입도 분포가 다를 수 있습니다. 미분은 막힘과 빠른 추출에, 큰 입자는 느린 내부 추출에 영향을 줍니다.",
    source: "grinder-basics",
    sourceLabel: "그라인더의 기본",
  },
  {
    id: "q-espresso-ratio",
    level: "입문",
    category: "추출",
    accent: "blue",
    question: "에스프레소 레시피를 재현할 때 '더블 샷'보다 유용한 기록은?",
    choices: ["잔의 색", "투입량과 음료량의 질량 비율", "머신의 판매 가격", "컵 손잡이 방향"],
    answer: 1,
    explanation:
      "샷 명칭과 잔 크기는 매장마다 다릅니다. 도징과 음료 수율을 그램으로 기록하면 농도와 추출 변화를 비교하기 쉽습니다.",
    source: "espresso-basics",
    sourceLabel: "에스프레소의 기본",
  },
  {
    id: "q-arabica-robusta",
    level: "입문",
    category: "산지와 생두",
    accent: "sage",
    question: "아라비카와 카네포라(로부스타)를 비교하는 올바른 태도는?",
    choices: ["종 이름만으로 품질을 확정한다", "유전·재배·가공과 시장 조건을 함께 본다", "카네포라는 카페인이 전혀 없다", "아라비카는 병해에 완전히 안전하다"],
    answer: 1,
    explanation:
      "종은 중요한 출발점이지만 품종, 환경, 수확과 가공, 로스팅이 실제 품질과 감각을 함께 만듭니다.",
    source: "arabica-and-robusta",
    sourceLabel: "아라비카와 로부스타",
  },
  {
    id: "q-variety-identity",
    level: "중급",
    category: "산지와 생두",
    accent: "sage",
    question: "품종 이름을 컵의 향미 보증서처럼 쓸 수 없는 이유는?",
    choices: ["품종은 식물과 관계없는 광고어이기 때문에", "유전형과 환경·관리·가공이 상호작용하기 때문에", "모든 품종의 유전자가 같기 때문에", "품종은 로스팅 후 바뀌기 때문에"],
    answer: 1,
    explanation:
      "품종은 잠재력을 설명하지만 동일 품종도 환경과 생산 공정에 따라 수량, 병 저항성과 향미가 달라집니다.",
    source: "coffee-varieties",
    sourceLabel: "커피 품종",
  },
  {
    id: "q-aroma-system",
    level: "전문",
    category: "커피 과학",
    accent: "blue",
    question: "기기에서 향기 분자가 검출되었을 때 사람의 지각을 판단하려면 무엇을 더 봐야 합니까?",
    choices: ["분자 이름의 길이", "농도, 감각 역치와 혼합물 상호작용", "컵의 가격만", "원두의 크기만"],
    answer: 1,
    explanation:
      "검출 여부만으로 감각 기여를 단정할 수 없습니다. 농도 대비 역치, 다른 성분과의 억제·증강, 패널 평가가 필요합니다.",
    source: "coffee-aroma-chemistry",
    sourceLabel: "커피 향미의 화학",
  },
  {
    id: "q-history-power",
    level: "중급",
    category: "커피 역사와 문화",
    accent: "copper",
    question: "커피의 세계사를 책임 있게 읽는 질문은?",
    choices: ["어느 전설이 가장 재미있는가", "누가 토지·노동·가격 위험을 부담했는가", "가장 비싼 잔은 무엇인가", "모든 지역의 음용법이 같은가"],
    answer: 1,
    explanation:
      "커피 문화의 확산은 식민지 토지와 강제노동, 무역 권력의 재편과 분리해 설명할 수 없습니다.",
    source: "global-coffee-history",
    sourceLabel: "커피 세계사",
  },
  {
    id: "q-climate-resilience",
    level: "전문",
    category: "지속가능성과 거래",
    accent: "sage",
    question: "커피 농장의 기후 회복탄력성을 가장 잘 설명한 것은?",
    choices: ["내열성 품종 하나로 완성된다", "유전·생태·소득·금융과 구매 관계가 함께 만든다", "고도를 높이면 비용 없이 해결된다", "탄소 숫자 하나만 낮추면 된다"],
    answer: 1,
    explanation:
      "품종과 농법은 중요하지만 장기 투자 여력, 가격 위험과 계약까지 함께 바뀌어야 농가가 적응할 수 있습니다.",
    source: "coffee-climate-resilience",
    sourceLabel: "기후위기와 커피",
  },
  {
    id: "q-caffeine-unit",
    level: "입문",
    category: "커피와 건강",
    accent: "olive",
    question: "카페인 섭취를 기록할 때 '커피 세 잔'보다 나은 방법은?",
    choices: ["잔 색깔만 적는다", "용량·제품별 추정량·시각과 모든 공급원을 기록한다", "에스프레소는 항상 0mg으로 센다", "주말 섭취는 제외한다"],
    answer: 1,
    explanation:
      "잔과 레시피에 따라 총 카페인이 크게 달라집니다. 차, 초콜릿, 에너지음료와 의약품까지 합산해야 합니다.",
    source: "caffeine-and-health",
    sourceLabel: "카페인과 건강",
  },
];
