export type ResourceKind = "논문" | "서적" | "표준·보고서" | "강의";

export type CoffeeResource = {
  id: string;
  kind: ResourceKind;
  title: string;
  citation: string;
  description: string;
  url: string;
  categories: string[];
  openAccess?: boolean;
};

export const resources: CoffeeResource[] = [
  {
    id: "farah-2019",
    kind: "서적",
    title: "Coffee: Production, Quality and Chemistry",
    citation: "Farah, A. (ed.). Royal Society of Chemistry, 2019. DOI 10.1039/9781782622437.",
    description: "식물·가공·로스팅·화학·건강까지 800쪽 이상으로 다루는 연구자용 종합 참고서입니다.",
    url: "https://doi.org/10.1039/9781782622437",
    categories: ["커피 기초", "산지와 생두", "로스팅", "추출", "커피 과학"],
  },
  {
    id: "folmer-2017",
    kind: "서적",
    title: "The Craft and Science of Coffee",
    citation: "Folmer, B. (ed.). Elsevier/Academic Press, 2017. ISBN 978-0-12-803520-7.",
    description: "생산자·연구자·로스터·바리스타의 관점을 씨앗에서 소비까지 연결하는 종합서입니다.",
    url: "https://www.educate.elsevier.com/book/details/9780128035207",
    categories: ["커피 기초", "산지와 생두", "로스팅", "추출", "커피 역사와 문화", "지속가능성과 거래"],
  },
  {
    id: "illy-viani-2005",
    kind: "서적",
    title: "Espresso Coffee: The Science of Quality (2nd ed.)",
    citation: "Illy, A. & Viani, R. (eds.). Elsevier/Academic Press, 2005. ISBN 978-0-12-370371-2.",
    description: "생두부터 로스팅, 분쇄, 패키징, 퍼콜레이션과 잔의 품질까지 에스프레소 기술을 체계화합니다.",
    url: "https://books.google.com/books/about/Espresso_Coffee.html?id=AJdlfSFCmVIC",
    categories: ["로스팅", "추출", "카페와 장비", "커피 과학"],
  },
  {
    id: "morris-2018",
    kind: "서적",
    title: "Coffee: A Global History",
    citation: "Morris, J. Reaktion Books, 2018. ISBN 978-1-78914-002-6.",
    description: "커피의 생산, 기술과 소비 문화가 세계 여러 지역에서 변화한 과정을 간결하게 연결합니다.",
    url: "https://reaktionbooks.co.uk/work/coffee",
    categories: ["커피 역사와 문화", "음료와 레시피", "지속가능성과 거래"],
  },
  {
    id: "hattox-1985",
    kind: "서적",
    title: "Coffee and Coffeehouses",
    citation: "Hattox, R. S. University of Washington Press, 1985. ISBN 978-0-295-96231-3.",
    description: "중세 근동에서 커피 음료와 커피하우스가 형성된 과정을 문헌 사료로 추적합니다.",
    url: "https://uwapress.uw.edu/book/9780295962313/coffee-and-coffeehouses/",
    categories: ["커피 역사와 문화", "음료와 레시피"],
  },
  {
    id: "sca-sensory-handbook",
    kind: "서적",
    title: "Coffee Sensory and Cupping Handbook",
    citation: "Fernández-Alduenda, M. & Giuliano, P. Specialty Coffee Association, 2021.",
    description: "감각과학의 원리와 커핑 실무, 향미 언어를 함께 설명하는 SCA 공식 핸드북입니다.",
    url: "https://sca.coffee/sca-news/read/announcement/just-published-the-new-coffee-sensory-and-cupping-handbook-2yg3l",
    categories: ["센서리", "카페 운영과 품질"],
  },
  {
    id: "gloess-2013",
    kind: "논문",
    title: "Comparison of nine common coffee extraction methods",
    citation: "Gloess, A. N. et al. European Food Research and Technology 236, 607–627 (2013). DOI 10.1007/s00217-013-1917-x.",
    description: "아홉 가지 추출법의 화학 성분과 감각 특성을 같은 틀에서 비교한 오픈 액세스 연구입니다.",
    url: "https://doi.org/10.1007/s00217-013-1917-x",
    categories: ["추출", "센서리", "커피 과학"],
    openAccess: true,
  },
  {
    id: "hendon-2014",
    kind: "논문",
    title: "The Role of Dissolved Cations in Coffee Extraction",
    citation: "Hendon, C. H., Colonna-Dashwood, L. & Williams, A. P. Journal of Agricultural and Food Chemistry 62, 4947–4950 (2014). DOI 10.1021/jf501687c.",
    description: "물속 양이온과 커피 성분의 상호작용을 계산화학으로 설명한 물 연구의 출발점입니다.",
    url: "https://doi.org/10.1021/jf501687c",
    categories: ["추출", "커피 과학"],
  },
  {
    id: "uekers-2016",
    kind: "논문",
    title: "The effect of bean origin and temperature on grinding roasted coffee",
    citation: "Uman, E. et al. Scientific Reports 6, 24483 (2016). DOI 10.1038/srep24483.",
    description: "원두의 온도와 산지가 분쇄 입도 분포에 미치는 영향을 정량적으로 살핍니다.",
    url: "https://doi.org/10.1038/srep24483",
    categories: ["추출", "카페와 장비", "커피 과학"],
    openAccess: true,
  },
  {
    id: "fuller-rao-2017",
    kind: "논문",
    title: "The effect of time, roasting temperature, and grind size on cold brew coffee",
    citation: "Fuller, M. & Rao, N. Z. Scientific Reports 7, 17979 (2017). DOI 10.1038/s41598-017-18247-4.",
    description: "콜드브루의 시간·로스팅·분쇄도가 카페인과 클로로젠산 농도에 미치는 영향을 분석합니다.",
    url: "https://doi.org/10.1038/s41598-017-18247-4",
    categories: ["추출", "로스팅", "커피 과학"],
    openAccess: true,
  },
  {
    id: "guinard-2023",
    kind: "논문",
    title: "A new Coffee Brewing Control Chart",
    citation: "Guinard, J.-X. et al. Journal of Food Science 88, 2308–2320 (2023). DOI 10.1111/1750-3841.16531.",
    description: "농도·수율과 감각 속성, 소비자 선호의 관계가 단순한 최적 상자보다 복잡함을 보여줍니다.",
    url: "https://doi.org/10.1111/1750-3841.16531",
    categories: ["추출", "센서리", "커피 과학"],
  },
  {
    id: "sunarharum-2014",
    kind: "논문",
    title: "Complexity of coffee flavor: A compositional and sensory perspective",
    citation: "Sunarharum, W. B., Williams, D. J. & Smyth, H. E. Food Research International 62, 315–325 (2014). DOI 10.1016/j.foodres.2014.02.030.",
    description: "향미를 만드는 휘발성·비휘발성 성분과 감각 지각을 연결해 검토한 리뷰입니다.",
    url: "https://doi.org/10.1016/j.foodres.2014.02.030",
    categories: ["센서리", "로스팅", "커피 과학"],
  },
  {
    id: "davis-2012",
    kind: "논문",
    title: "The Impact of Climate Change on Indigenous Arabica Coffee",
    citation: "Davis, A. P. et al. PLOS ONE 7(11), e47981 (2012). DOI 10.1371/journal.pone.0047981.",
    description: "기후변화가 야생 아라비카의 적합 서식지에 미칠 영향을 모델링한 대표 연구입니다.",
    url: "https://doi.org/10.1371/journal.pone.0047981",
    categories: ["산지와 생두", "지속가능성과 거래"],
    openAccess: true,
  },
  {
    id: "bunn-2015",
    kind: "논문",
    title: "A bitter cup: climate change profile of global production of Arabica and Robusta coffee",
    citation: "Bunn, C. et al. Climatic Change 129, 89–101 (2015). DOI 10.1007/s10584-014-1306-x.",
    description: "아라비카와 로부스타 재배 적합지가 기후 시나리오에 따라 어떻게 달라지는지 비교합니다.",
    url: "https://doi.org/10.1007/s10584-014-1306-x",
    categories: ["산지와 생두", "지속가능성과 거래"],
  },
  {
    id: "farah-donangelo-2006",
    kind: "논문",
    title: "Phenolic compounds in coffee",
    citation: "Farah, A. & Donangelo, C. M. Brazilian Journal of Plant Physiology 18, 23–36 (2006). DOI 10.1590/S1677-04202006000100003.",
    description: "생두와 로스팅 커피의 주요 페놀 화합물, 변화와 생리 활성을 정리한 오픈 리뷰입니다.",
    url: "https://doi.org/10.1590/S1677-04202006000100003",
    categories: ["커피 기초", "로스팅", "커피 과학"],
    openAccess: true,
  },
  {
    id: "efsa-caffeine",
    kind: "표준·보고서",
    title: "Scientific Opinion on the Safety of Caffeine",
    citation: "EFSA NDA Panel. EFSA Journal 13(5):4102 (2015). DOI 10.2903/j.efsa.2015.4102.",
    description: "건강한 성인, 임신·수유, 어린이와 청소년의 카페인 안전성을 용량별로 평가한 공식 의견입니다.",
    url: "https://www.efsa.europa.eu/en/topics/topic/caffeine",
    categories: ["커피와 건강", "커피 과학"],
    openAccess: true,
  },
  {
    id: "fda-caffeine",
    kind: "표준·보고서",
    title: "Spilling the Beans: How Much Caffeine is Too Much?",
    citation: "U.S. Food and Drug Administration. Consumer Update, current edition.",
    description: "대부분의 성인에 대한 하루 400mg 참고선과 개인차, 과다 섭취 증상을 설명합니다.",
    url: "https://www.fda.gov/consumers/consumer-updates/spilling-beans-how-much-caffeine-too-much",
    categories: ["커피와 건강"],
    openAccess: true,
  },
  {
    id: "who-caffeine-pregnancy",
    kind: "표준·보고서",
    title: "Restricting caffeine intake during pregnancy",
    citation: "World Health Organization. eLENA intervention guidance, updated 2023.",
    description: "임신 중 고카페인 섭취와 섭취 저감 권고의 대상, 근거와 조건을 안내합니다.",
    url: "https://www.who.int/tools/elena/interventions/caffeine-pregnancy",
    categories: ["커피와 건강"],
    openAccess: true,
  },
  {
    id: "sca-standards",
    kind: "표준·보고서",
    title: "SCA Coffee Standards",
    citation: "Specialty Coffee Association. Standards & Procedures, current edition.",
    description: "CVA 시료 준비·기술 평가·선호 평가 등 현재 공식 표준과 개정 상태를 확인하는 기준 페이지입니다.",
    url: "https://sca.coffee/research/coffee-standards",
    categories: ["센서리", "추출", "카페 운영과 품질"],
    openAccess: true,
  },
  {
    id: "wcr-lexicon",
    kind: "표준·보고서",
    title: "World Coffee Research Sensory Lexicon 2.0",
    citation: "World Coffee Research & Kansas State University Sensory Analysis Center, 2017.",
    description: "110개 향·맛·질감 속성의 정의, 강도 기준과 실제 참조물을 제공하는 감각과학 도구입니다.",
    url: "https://worldcoffeeresearch.org/read-more/news/174-world-coffee-research-sensory-lexicon",
    categories: ["센서리", "커피 과학"],
    openAccess: true,
  },
  {
    id: "wcr-catalog",
    kind: "표준·보고서",
    title: "World Coffee Research Coffee Varieties Catalog",
    citation: "World Coffee Research. Arabica and Robusta Coffee Varieties Catalog.",
    description: "아라비카 55종과 로부스타 47종의 계통·수량·고도·병해 저항성 정보를 공개한 품종 카탈로그입니다.",
    url: "https://worldcoffeeresearch.org/resources/coffee-varieties-catalog",
    categories: ["산지와 생두", "지속가능성과 거래"],
    openAccess: true,
  },
  {
    id: "ico-cdr-2022",
    kind: "표준·보고서",
    title: "Coffee Development Report 2022–23",
    citation: "International Coffee Organization. Beyond Coffee: Towards a Circular Economy in Coffee, 2024.",
    description: "생산부터 소비까지 부산물, 순환경제, 재생농업과 시장 데이터를 다루는 ICO 대표 보고서입니다.",
    url: "https://ico.org/coffee-development-report-2/",
    categories: ["지속가능성과 거래", "산지와 생두", "커피 역사와 문화"],
    openAccess: true,
  },
  {
    id: "sca-education",
    kind: "강의",
    title: "SCA Education",
    citation: "Specialty Coffee Association. Skills courses, diplomas, Q Grader and business education.",
    description: "브루잉·로스팅·센서리·그린 커피·바리스타·카페 비즈니스의 공식 교육 경로를 찾을 수 있습니다.",
    url: "https://sca.coffee/education",
    categories: ["추출", "로스팅", "센서리", "카페와 장비", "카페 운영과 품질"],
  },
  {
    id: "ucd-coffee",
    kind: "강의",
    title: "UC Davis Coffee Center Education",
    citation: "University of California, Davis Coffee Center.",
    description: "대학 학부 과정, 평생교육과 연구 기반 커피 교육 프로그램을 안내합니다.",
    url: "https://coffeecenter.ucdavis.edu/education",
    categories: ["커피 과학", "추출", "센서리", "카페 운영과 품질"],
  },
  {
    id: "wcr-learning",
    kind: "강의",
    title: "World Coffee Research 공개 학습 자료",
    citation: "World Coffee Research. Resources and research programs.",
    description: "품종, 육종, 농가 실험과 감각 데이터에 관한 공개 자료를 연구 프로젝트와 함께 탐색합니다.",
    url: "https://worldcoffeeresearch.org/work",
    categories: ["산지와 생두", "지속가능성과 거래", "센서리"],
    openAccess: true,
  },
];

export function resourcesForCategory(category: string, limit = 6) {
  const matched = resources.filter((resource) =>
    resource.categories.includes(category),
  );
  return matched.slice(0, limit);
}
