#!/usr/bin/env node
// Generates src/content/articles/index.ts from the .md sources (in order.json).
// Output is plain typed data — no runtime fs, so it bundles for both server and
// client and works even on the on-demand /tags route. Runs in predev/prebuild.

import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { markdownToArticle } from "./content-md.mjs";

const dir = join(process.cwd(), "src", "content", "articles");

const order = JSON.parse(readFileSync(join(dir, "order.json"), "utf8"));
const mdSlugs = readdirSync(dir)
  .filter((f) => f.endsWith(".md"))
  .map((f) => f.replace(/\.md$/, ""));

// order.json and the .md files must agree exactly.
for (const slug of order) {
  if (!mdSlugs.includes(slug))
    throw new Error(`order.json lists "${slug}" but ${slug}.md is missing`);
}
for (const slug of mdSlugs) {
  if (!order.includes(slug))
    throw new Error(`${slug}.md exists but is not listed in order.json`);
}

const articles = order.map((slug) =>
  markdownToArticle(readFileSync(join(dir, `${slug}.md`), "utf8")),
);

const header = `import type { Article } from "@/content/types";

// GENERATED by scripts/build-content.mjs from src/content/articles/*.md.
// Do not edit by hand — edit the .md files (and order.json), then run
// \`npm run build:content\` (also runs automatically on predev/prebuild).
`;

const out = `${header}\nexport const articles: Article[] = ${JSON.stringify(
  articles,
  null,
  2,
)};\n`;

writeFileSync(join(dir, "index.ts"), out, "utf8");
console.log(`✓ build-content: generated index.ts (${articles.length} articles)`);
