#!/usr/bin/env node
// Generates src/content/articles/index.ts from the .html sources. Emits a
// locale-keyed map (ko from articles/*.html, en from articles/en/*.html with a
// per-slug fallback to ko). Output is plain typed data — no runtime fs — so it
// bundles for both server and client and works on the on-demand /tags route.
// Runs in predev/prebuild.

import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import {
  articleFromSource,
  extractWikilinks,
  annotateRedLinks,
} from "../src/lib/content-serialize.mjs";

const dir = join(process.cwd(), "src", "content", "articles");
const enDir = join(dir, "en");

const order = JSON.parse(readFileSync(join(dir, "order.json"), "utf8"));

const load = (path) => articleFromSource(readFileSync(path, "utf8"));

const ko = order.map((slug) => load(join(dir, `${slug}.html`)));
// English: use the translated file when present, otherwise fall back to Korean.
const en = order.map((slug) => {
  const enPath = join(enDir, `${slug}.html`);
  return existsSync(enPath) ? load(enPath) : load(join(dir, `${slug}.html`));
});

// Wikilinks: compute backlinks (who links here) and mark red links (targets
// that don't exist) per locale. Slugs are shared across locales.
const slugSet = new Set(order);
const exists = (slug) => slugSet.has(slug);
for (const set of [ko, en]) {
  const backlinks = {};
  for (const a of set)
    for (const target of extractWikilinks(a.bodyHtml)) {
      (backlinks[target] ??= []).push(a.slug);
    }
  for (const a of set) {
    a.bodyHtml = annotateRedLinks(a.bodyHtml, exists);
    a.backlinks = backlinks[a.slug] ?? [];
  }
}

const header = `import type { Article } from "@/content/types";

// GENERATED by scripts/build-content.mjs from src/content/articles/*.html
// (and en/*.html). Do not edit by hand — edit the .html files (and order.json),
// then run \`npm run build:content\` (also runs automatically on predev/prebuild).
`;

const out = `${header}\nexport const articlesByLocale: Record<string, Article[]> = {
  ko: ${JSON.stringify(ko, null, 2)},
  en: ${JSON.stringify(en, null, 2)},
};\n`;

writeFileSync(join(dir, "index.ts"), out, "utf8");
console.log(
  `✓ build-content: generated index.ts (ko: ${ko.length}, en: ${en.length})`,
);
