#!/usr/bin/env node
// Generates src/content/articles/index.ts from the .md sources. Emits a
// locale-keyed map (ko from articles/*.md, en from articles/en/*.md with a
// per-slug fallback to ko). Output is plain typed data — no runtime fs — so it
// bundles for both server and client and works on the on-demand /tags route.
// Runs in predev/prebuild.

import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { markdownToArticle } from "./content-md.mjs";

const dir = join(process.cwd(), "src", "content", "articles");
const enDir = join(dir, "en");

const order = JSON.parse(readFileSync(join(dir, "order.json"), "utf8"));

const load = (path) => markdownToArticle(readFileSync(path, "utf8"));

const ko = order.map((slug) => load(join(dir, `${slug}.md`)));
// English: use the translated file when present, otherwise fall back to Korean.
const en = order.map((slug) => {
  const enPath = join(enDir, `${slug}.md`);
  return existsSync(enPath) ? load(enPath) : load(join(dir, `${slug}.md`));
});

const header = `import type { Article } from "@/content/types";

// GENERATED by scripts/build-content.mjs from src/content/articles/*.md
// (and en/*.md). Do not edit by hand — edit the .md files (and order.json),
// then run \`npm run build:content\` (also runs automatically on predev/prebuild).
`;

const out = `${header}\nexport const articlesByLocale: Record<string, Article[]> = {
  ko: ${JSON.stringify(ko, null, 2)},
  en: ${JSON.stringify(en, null, 2)},
};\n`;

writeFileSync(join(dir, "index.ts"), out, "utf8");
console.log(
  `✓ build-content: generated index.ts (ko: ${ko.length}, en: ${en.length})`,
);
